language: python
python:
  - "3.8"
before_install:
  - "pip install -U pip"
  - "python setup.py install"
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=tests --cov-reports=xml
env:
  - CODECOV_TOKEN=e6bedb1f-78d0-4f2c-b053-ab72b73b5451
notifications:
  email:
    on_success: never
    on_failure: always
after_success:
  - codecov